### ISSUE TITLE
Unexplicit error message displayed when there is a Mysql error

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#38]
# Scenario
1) Shutdown your mysql service by typing `sudo service mysql stop`
2) Go to the login page
3) Try to log in with any user

# Expected behavior
We should see an error message telling something went wrong when trying to connect

# Current behavior
The user can see the Mysql Error message :
![mysql error message when you try to log in with no mysql service](https://user-images.githubusercontent.com/50443097/59096799-035c9700-891c-11e9-8538-6c826507a9bf.png)

**Comment by Yann-BUTSCHER-EIRL** [comment]
We should put more try/catch and maybe specify witch error we try to catch (For exemple, connection refused, etc...)

**Comment by LucileDT** [comment]
Do you think it would be different in prod env, like maybe the message would not be thrown that way because in prod env, debug is disabled?

I totally agree with you that we need a better try catch.

This issue is bigger than you think: if we start to catch errors, we need to create a documentation with error codes, so that when there is an error, the user see `An error happened (error code: 48117), please contact your administrator.`, which would allow us to know what happened using the error code to find the corresponding issue. So maybe we should talk more about it and create another issue (feature type) about creating this document and the documentation explaining how to use it?

**Comment by LucileDT** [comment]
Created #57 about the error codes thing. #38 will only covers the mysql connection error problem.

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT Opened an issue on Symfony's GitHub, addressing the problem : 
https://github.com/symfony/symfony/issues/32547

**Comment by LucileDT** [comment]
Answers in the issue I opened are not very helping (and it has been closed because "it works as expected" :frowning_face:).

I think for now we will do something like this:
```php
if ($authenticationUtils->getLastAuthenticationError()->getMessage() === 'An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused')
{
    $this->addFlash(
        'danger', 'A problem have been encountered, please contact your administrator (error code: 487 125).'
    );
}
```
